export const API_BASE_URL = 'http://localhost/Yoga_Web/Yoga_Backend';

export const endpoints = {
    login: `${API_BASE_URL}/auth/login`,
    forgotPassword: `${API_BASE_URL}/auth/forgotPassword`,
    resetPassword: `${API_BASE_URL}/auth/resetPassword`,
    courses: `${API_BASE_URL}/courses`,
    settings: `${API_BASE_URL}/settings`,
    content: `${API_BASE_URL}/content/home`,
    syllabusContent: `${API_BASE_URL}/content/syllabus`,
    resultsContent: `${API_BASE_URL}/content/results`,
    examDatesContent: `${API_BASE_URL}/content/examDates`,
    examEligibilityContent: `${API_BASE_URL}/content/examEligibility`,
    admitCardContent: `${API_BASE_URL}/content/admitCard`,
    admitCardsList: `${API_BASE_URL}/AdmitCards`,
    admitCardsCreate: `${API_BASE_URL}/AdmitCards/create`,
    admitCardsUpdate: `${API_BASE_URL}/AdmitCards/update`,
    admitCardsDelete: `${API_BASE_URL}/AdmitCards/delete`,
    admitCardsSearch: `${API_BASE_URL}/AdmitCards/search`,
    resultsList: `${API_BASE_URL}/results`,
    resultsCreate: `${API_BASE_URL}/results/create`,
    resultsDelete: `${API_BASE_URL}/results/delete`,
    mediaList: `${API_BASE_URL}/media`,
    mediaUpload: `${API_BASE_URL}/media/upload`,
    mediaDelete: `${API_BASE_URL}/media/delete`,
    resourcesList: `${API_BASE_URL}/resources`,
    resourcesCreate: `${API_BASE_URL}/resources/create`,
    resourcesDelete: `${API_BASE_URL}/resources/delete`,
    curriculumList: `${API_BASE_URL}/curriculum`,
    curriculumSave: `${API_BASE_URL}/curriculum/save`,
    curriculumDelete: `${API_BASE_URL}/curriculum/delete`,
    trainingList: `${API_BASE_URL}/training`,
    trainingCreate: `${API_BASE_URL}/training/create`,
    trainingDelete: `${API_BASE_URL}/training/delete`,
    teacherResourcesList: `${API_BASE_URL}/TeacherResources`,
    teacherResourcesCreate: `${API_BASE_URL}/TeacherResources/create`,
    teacherResourcesDelete: `${API_BASE_URL}/TeacherResources/delete`,
    examDatesList: `${API_BASE_URL}/ExamDates`,
    examDatesSave: `${API_BASE_URL}/ExamDates/save`,
    examDatesDelete: `${API_BASE_URL}/ExamDates/delete`,
    updateContent: `${API_BASE_URL}/content/update`,
};
